application:
  basename: tika-server
  environment: DEV

logging:
  level:
    com:
      k2:
        tika-server: TRACE

server:
  servlet:
    session:
      cookie:
        http-only: "true"
  session:
    tracking-modes: cookie
  error:
    path: /error
  port: "8085"

spring:
  servlet:
    multipart:
      enabled: "true"
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: "false"

nlp:
  nlpRootLocation: /local/home/nlp-data-root/nlp
  tokenizerModel: eng-token.bin
  taggerModel: eng-pos-maxent.bin
  languageModel: lang-detect.bin
  sentModel: eng-sent.bin
  lemmatizerModel: eng-lemmatizer.bin
  lemmatizerDict: eng-lemmatizer.dict
  chunkerModel: eng-chunker.bin
